---
output:
  pdf_document: default
  word_document: default
  html_document: default
---
# EpiBuffer: Spatially-Varying Buffer Radii Model for Estimating Spatial Heterogeneity in Exposure Buffers and Risk


## SingleBuffer Statistical Model

$$
Y_i\left(\textbf{s}_j\right) | \mu_i\left(\textbf{s}_j\right), \boldsymbol{\zeta} \stackrel{\text{ind}}{\sim} f\left(y \mid \mu_i\left(\textbf{s}_j\right), \boldsymbol{\zeta} \right),\ j=1,...,m, \ i=1,...,n_j;
$$
$$
g\{\mu_i(\textbf{s}_j)\} = \text{O}_i(\textbf{s}_j) + \textbf{x}_i(\textbf{s}_j)^{\text{T}} \boldsymbol{\beta} + \text{z}(\textbf{s}_j; \delta) \eta.
$$

## Likelihood Options
* Binomial likelihood with logit link function (likelihood_indicator $= 0$): 
$$
Y_i(\textbf{s}_j) | p_i(\textbf{s}_j) \stackrel{\text{ind}}{\sim} \text{Binomial}\left(\tilde{n}_i(\textbf{s}_j), p_i(\textbf{s}_j)\right), \text{logit}\left\{p_i(\textbf{s}_j)\right\} = \textbf{x}_i(\textbf{s}_j)^{\text{T}}\boldsymbol{\beta} + \text{z}\left(\textbf{s}_j; \delta\right) \eta;
$$

* Gaussian likelihood with identity link function (likelihood_indicator $= 1$): 
$$
Y_i(\textbf{s}_j) = \textbf{x}_i(\textbf{s}_j)^{\text{T}}\boldsymbol{\beta} + \text{z}\left(\textbf{s}_j; \delta\right) \eta + \epsilon_i,\ \epsilon_i|\sigma^2_{\epsilon} \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\epsilon}\right);
$$

* Negative binomial likelihood with logit link function (likelihood_indicator $= 2$): 
$$
Y_i(\textbf{s}_j) | r, p_i(\textbf{s}_j) \stackrel{\text{ind}}{\sim} \text{Negative Binomial}\left(r, p_i(\textbf{s}_j)\right),
\text{logit}\left\{p_i(\textbf{s}_j)\right\} = \text{O}_i(\textbf{s}_j) + \textbf{x}_i(\textbf{s}_j)^{\text{T}}\boldsymbol{\beta} + \text{z}\left(\textbf{s}_j; \delta\right) \eta.
$$


## Exposure Definitions
* Counts (exposure_definition_indicator $= 0$):
$$\text{z}\left(\textbf{s}_j; \delta\right) = \sum_{k=1}^h 1(\text{d}_{jk} \leq \delta);$$

* Spherical (exposure_definition_indicator $= 1$):
$$\text{z}\left(\textbf{s}_j; \delta\right) = \sum\limits_{k=1}^{h} 1(\text{d}_{jk} \leq \delta) \left(1 - 1.5\left\{\frac{\text{d}_{jk}}{\delta}\right\} + 0.5\left\{\frac{\text{d}_{jk}}{\delta}\right\}^3\right);$$
        
*  Presence/absence (exposure_definition_indicator $= 2$):
$$\text{z}\left(\textbf{s}_j; \delta\right) = \text{min} \left(\sum_{k=1}^h 1\left(d_{jk} \leq \delta\right), 1\right);$$

    *  $\text{d}_{jk}$:  Distance between location $\textbf{s}_j$ and point source $\textbf{c}_k$;
    *  $h$:  Total number of point sources.

## Prior Information
$\beta_j \stackrel{\text{iid}}{\sim} \text{N}\left(\mathbf{0}, \sigma^2_{\beta}\right),\ j=1,\hdots,p_x$;

* $p_x$: Length of $\textbf{x}_i$ vector (same for all $i$), including an intercept;

* Default setting: $\sigma^2_{\beta} = 100^2$;

$\delta \sim \text{Uniform}\left(a_{\delta},b_{\delta}\right)$;

$\eta \sim \text{N} \left(0, \sigma^2_{\eta}\right)$;

* Default setting: $\sigma^2_{\eta} = 100^2$;

Gaussian specific:  $\sigma^2_{\epsilon} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\epsilon}}, b_{\sigma^2_{\epsilon}}\right)$;

* Default setting:  $a_{\sigma^2_{\epsilon}} = b_{\sigma^2_{\epsilon}} = 0.01$;

Negative binomial specific:  $r \sim \text{Discrete Uniform}\left[a_r, b_r\right]$;

* Default setting: $a_r = 1, b_r = 100$.


## Default Initial Values
* $\beta_j = 0$ for all $j$;

* $\delta = \frac{b_{\delta} - a_{\delta}}{2}$;

* $\eta = 0$;

* Gaussian specific: $\sigma^2_{\epsilon} = \text{variance}(\mathbf{Y})$;

* Negative binomial specific: $r= 100$.




\pagebreak

