#ifndef __EpiBuffer__
#define __EpiBuffer__

arma::vec rcpp_pgdraw(arma::vec b, 
                      arma::vec c);

Rcpp::NumericVector sampleRcpp(Rcpp::NumericVector x,
                               int size,
                               bool replace,
                               Rcpp::NumericVector prob = Rcpp::NumericVector::create());

Rcpp::List temporal_corr_fun(int m,
                             double rho_theta);

Rcpp::List spatial_corr_fun(double phi,
                            arma::mat spatial_dists);

double neg_two_loglike_update(arma::vec y,
                              arma::mat x,
                              arma::vec off_set,
                              arma::vec tri_als,
                              int likelihood_indicator,
                              int n_ind,
                              int r,
                              double sigma2_epsilon,
                              arma::vec beta,
                              arma::vec theta_keep,
                              arma::mat Z);

Rcpp::List latent_update(arma::vec y,
                         arma::mat x,
                         arma::vec off_set,
                         arma::vec tri_als,
                         int likelihood_indicator,
                         int n_ind,
                         int r_old,
                         arma::vec beta_old,
                         arma::vec theta_keep_old,
                         arma::mat Z);

double sigma2_epsilon_update(arma::vec y,
                             arma::mat x,
                             arma::vec off_set,
                             int n_ind,
                             double a_sigma2_epsilon,
                             double b_sigma2_epsilon,
                             arma::vec beta_old,
                             arma::vec theta_keep_old,
                             arma::mat Z);

int r_update(arma::vec y,
             arma::mat x,
             arma::vec off_set,
             int n_ind,
             int a_r,
             int b_r,
             arma::vec beta,
             arma::vec theta_keep,
             arma::mat Z);

arma::vec beta_update(arma::mat x,
                      arma::vec off_set,
                      int n_ind,
                      int p_x,
                      double sigma2_beta,
                      arma::vec omega,
                      arma::vec lambda,
                      arma::vec theta_keep_old,
                      arma::mat Z);

Rcpp::List theta_single_update(arma::mat x, 
                               arma::vec off_set,
                               int n_ind,
                               int m,
                               arma::vec omega,
                               arma::vec lambda,
                               arma::vec beta,
                               double sigma2_theta_old,
                               double rho_theta_old,
                               arma::mat theta_corr_inv,
                               arma::uvec radius_pointer_old, 
                               arma::mat Z);

Rcpp::List theta_update(arma::mat x, 
                        arma::vec off_set,
                        int n_ind,
                        int m,
                        arma::rowvec one_vec,
                        arma::vec omega,
                        arma::vec lambda,
                        arma::vec beta,
                        double sigma2_theta_old,
                        double rho_theta_old,
                        arma::mat theta_corr_inv,
                        arma::mat G,
                        arma::mat Z);

Rcpp::List theta_single_update(arma::mat x, 
                               arma::vec off_set,
                               int n_ind,
                               int m,
                               arma::vec omega,
                               arma::vec lambda,
                               arma::vec beta,
                               double sigma2_theta_old,
                               double rho_theta_old,
                               arma::mat theta_corr_inv,
                               double radius_pointer_old, 
                               arma::mat Z);

double sigma2_theta_update(int m,
                           double a_sigma2_theta,
                           double b_sigma2_theta,
                           arma::vec theta,
                           double rho_theta_old,
                           arma::mat theta_corr_inv);

Rcpp::List rho_theta_update(int m,
                            double l_rho_theta,
                            double u_rho_theta,
                            arma::vec theta,
                            double sigma2_theta,
                            double rho_theta_old,
                            Rcpp::List theta_corr_info,
                            double metrop_var_rho_theta,
                            int acctot_rho_theta_trans);

Rcpp::List gamma_update(arma::mat x,
                        arma::vec radius_seq,
                        arma::mat exposure,
                        arma::vec off_set,
                        arma::mat w,
                        int n_ind,
                        int m,
                        int p_w,
                        arma::rowvec one_vec,
                        double sigma2_gamma,
                        arma::vec omega,
                        arma::vec lambda,
                        arma::vec beta, 
                        arma::vec theta,
                        arma::vec gamma_old,
                        arma::vec phi_tilde,
                        arma::vec delta_star_trans,
                        arma::vec delta_star,
                        arma::vec radius_pointer,
                        arma::mat G,
                        arma::vec radius,
                        arma::mat Z,
                        arma::vec theta_keep,
                        arma::vec metrop_var_gamma,
                        arma::vec acctot_gamma);

Rcpp::List radius_update(arma::vec y,
                         arma::mat x,
                         arma::vec radius_seq,
                         arma::mat exposure,
                         arma::vec off_set,
                         arma::vec tri_als,
                         int likelihood_indicator,
                         int n_ind,
                         int m,
                         int r_old,
                         double sigma2_epsilon,
                         arma::vec beta, 
                         arma::vec theta,
                         arma::vec radius,
                         arma::mat Z,
                         arma::vec theta_keep);

Rcpp::List phi_star_update(arma::mat x,
                           arma::vec radius_seq,
                           arma::mat exposure,
                           arma::vec off_set,
                           arma::mat w,
                           int n_ind,
                           int n_grid,
                           int m,
                           arma::rowvec one_vec,
                           arma::vec omega,
                           arma::vec lambda,
                           arma::vec beta, 
                           arma::vec theta,
                           arma::vec gamma,
                           arma::vec phi_star_old,
                           double sigma2_phi_old,
                           arma::mat phi_star_corr_inv,
                           arma::mat C,
                           arma::vec phi_tilde,
                           arma::vec delta_star_trans,
                           arma::vec delta_star,
                           arma::vec radius_pointer,
                           arma::mat G,
                           arma::vec radius,
                           arma::mat Z,
                           arma::vec theta_keep,
                           arma::vec metrop_var_phi_star,
                           arma::vec acctot_phi_star);

double sigma2_phi_update(int n_grid,
                         double a_sigma2_phi,
                         double b_sigma2_phi,
                         arma::vec phi_star,
                         arma::mat phi_star_corr_inv);

Rcpp::List rho_phi_update(arma::mat x,
                          arma::vec radius_seq,
                          arma::mat exposure,
                          arma::vec off_set,
                          arma::mat w,
                          int n_ind,
                          int m,
                          arma::mat dists12,
                          arma::mat dists22,
                          arma::rowvec one_vec,
                          double a_rho_phi,
                          double b_rho_phi,
                          arma::vec omega,
                          arma::vec lambda,
                          arma::vec beta, 
                          arma::vec theta,
                          arma::vec gamma,
                          arma::vec phi_star,
                          double sigma2_phi,
                          double rho_phi_old,
                          Rcpp::List phi_star_corr_info,
                          arma::mat C,
                          arma::vec phi_tilde,
                          arma::vec delta_star_trans,
                          arma::vec delta_star,
                          arma::vec radius_pointer,
                          arma::mat G,
                          arma::vec radius,
                          arma::mat Z,
                          arma::vec theta_keep,
                          double metrop_var_rho_phi,
                          int acctot_rho_phi);

Rcpp::List SingleBuffer(int mcmc_samples,
                        arma::vec y,
                        arma::mat x,
                        arma::vec radius_seq,
                        arma::mat exposure,
                        double metrop_var_rho_theta,
                        int likelihood_indicator,
                        Rcpp::Nullable<Rcpp::NumericVector> offset,
                        Rcpp::Nullable<Rcpp::NumericVector> trials,
                        Rcpp::Nullable<double> a_r_prior,
                        Rcpp::Nullable<double> b_r_prior,
                        Rcpp::Nullable<double> a_sigma2_epsilon_prior,
                        Rcpp::Nullable<double> b_sigma2_epsilon_prior,
                        Rcpp::Nullable<double> sigma2_beta_prior,
                        Rcpp::Nullable<double> a_sigma2_theta_prior,
                        Rcpp::Nullable<double> b_sigma2_theta_prior,
                        Rcpp::Nullable<double> l_rho_theta_prior,
                        Rcpp::Nullable<double> u_rho_theta_prior,
                        Rcpp::Nullable<double> r_init,
                        Rcpp::Nullable<double> sigma2_epsilon_init,
                        Rcpp::Nullable<Rcpp::NumericVector> beta_init,
                        Rcpp::Nullable<double> theta_keep_init,
                        Rcpp::Nullable<double> sigma2_theta_init,
                        Rcpp::Nullable<double> rho_theta_init,
                        Rcpp::Nullable<double> radius_pointer_init);

Rcpp::List SpatialBuffers(int mcmc_samples,
                          arma::vec y,
                          arma::mat x,
                          arma::vec radius_seq,
                          arma::mat exposure,
                          arma::mat w,
                          arma::mat full_dists,
                          double metrop_var_rho_theta,
                          arma::vec metrop_var_gamma,
                          arma::vec metrop_var_phi_star,
                          double metrop_var_rho_phi,
                          int likelihood_indicator,
                          Rcpp::Nullable<Rcpp::NumericVector> offset,
                          Rcpp::Nullable<Rcpp::NumericVector> trials,
                          Rcpp::Nullable<double> a_r_prior,
                          Rcpp::Nullable<double> b_r_prior,
                          Rcpp::Nullable<double> a_sigma2_epsilon_prior,
                          Rcpp::Nullable<double> b_sigma2_epsilon_prior,
                          Rcpp::Nullable<double> sigma2_beta_prior,
                          Rcpp::Nullable<double> a_sigma2_theta_prior,
                          Rcpp::Nullable<double> b_sigma2_theta_prior,
                          Rcpp::Nullable<double> l_rho_theta_prior,
                          Rcpp::Nullable<double> u_rho_theta_prior,
                          Rcpp::Nullable<double> sigma2_gamma_prior,
                          Rcpp::Nullable<double> a_sigma2_phi_prior,
                          Rcpp::Nullable<double> b_sigma2_phi_prior,
                          Rcpp::Nullable<double> a_rho_phi_prior,
                          Rcpp::Nullable<double> b_rho_phi_prior,
                          Rcpp::Nullable<double> r_init,
                          Rcpp::Nullable<double> sigma2_epsilon_init,
                          Rcpp::Nullable<Rcpp::NumericVector> beta_init,
                          Rcpp::Nullable<double> theta_keep_init,
                          Rcpp::Nullable<double> sigma2_theta_init,
                          Rcpp::Nullable<double> rho_theta_init,
                          Rcpp::Nullable<Rcpp::NumericVector> gamma_init,
                          Rcpp::Nullable<double> sigma2_phi_init,
                          Rcpp::Nullable<double> rho_phi_init);

#endif // __EpiBuffer__
