// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SingleBuffer
Rcpp::List SingleBuffer(int mcmc_samples, arma::vec y, arma::mat x, arma::vec radius_seq, arma::mat exposure, double metrop_var_rho_theta, int likelihood_indicator, Rcpp::Nullable<Rcpp::NumericVector> offset, Rcpp::Nullable<Rcpp::NumericVector> trials, Rcpp::Nullable<double> a_r_prior, Rcpp::Nullable<double> b_r_prior, Rcpp::Nullable<double> a_sigma2_epsilon_prior, Rcpp::Nullable<double> b_sigma2_epsilon_prior, Rcpp::Nullable<double> sigma2_beta_prior, Rcpp::Nullable<double> a_sigma2_theta_prior, Rcpp::Nullable<double> b_sigma2_theta_prior, Rcpp::Nullable<double> l_rho_theta_prior, Rcpp::Nullable<double> u_rho_theta_prior, Rcpp::Nullable<double> r_init, Rcpp::Nullable<double> sigma2_epsilon_init, Rcpp::Nullable<Rcpp::NumericVector> beta_init, Rcpp::Nullable<double> theta_keep_init, Rcpp::Nullable<double> sigma2_theta_init, Rcpp::Nullable<double> rho_theta_init, Rcpp::Nullable<double> radius_pointer_init);
RcppExport SEXP _SpBuffer_SingleBuffer(SEXP mcmc_samplesSEXP, SEXP ySEXP, SEXP xSEXP, SEXP radius_seqSEXP, SEXP exposureSEXP, SEXP metrop_var_rho_thetaSEXP, SEXP likelihood_indicatorSEXP, SEXP offsetSEXP, SEXP trialsSEXP, SEXP a_r_priorSEXP, SEXP b_r_priorSEXP, SEXP a_sigma2_epsilon_priorSEXP, SEXP b_sigma2_epsilon_priorSEXP, SEXP sigma2_beta_priorSEXP, SEXP a_sigma2_theta_priorSEXP, SEXP b_sigma2_theta_priorSEXP, SEXP l_rho_theta_priorSEXP, SEXP u_rho_theta_priorSEXP, SEXP r_initSEXP, SEXP sigma2_epsilon_initSEXP, SEXP beta_initSEXP, SEXP theta_keep_initSEXP, SEXP sigma2_theta_initSEXP, SEXP rho_theta_initSEXP, SEXP radius_pointer_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mcmc_samples(mcmc_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_seq(radius_seqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_rho_theta(metrop_var_rho_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type likelihood_indicator(likelihood_indicatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type trials(trialsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_r_prior(a_r_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_r_prior(b_r_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_epsilon_prior(a_sigma2_epsilon_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_epsilon_prior(b_sigma2_epsilon_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_beta_prior(sigma2_beta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_theta_prior(a_sigma2_theta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_theta_prior(b_sigma2_theta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type l_rho_theta_prior(l_rho_theta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type u_rho_theta_prior(u_rho_theta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type r_init(r_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_epsilon_init(sigma2_epsilon_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type theta_keep_init(theta_keep_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_theta_init(sigma2_theta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type rho_theta_init(rho_theta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type radius_pointer_init(radius_pointer_initSEXP);
    rcpp_result_gen = Rcpp::wrap(SingleBuffer(mcmc_samples, y, x, radius_seq, exposure, metrop_var_rho_theta, likelihood_indicator, offset, trials, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_beta_prior, a_sigma2_theta_prior, b_sigma2_theta_prior, l_rho_theta_prior, u_rho_theta_prior, r_init, sigma2_epsilon_init, beta_init, theta_keep_init, sigma2_theta_init, rho_theta_init, radius_pointer_init));
    return rcpp_result_gen;
END_RCPP
}
// SpatialBuffers
Rcpp::List SpatialBuffers(int mcmc_samples, arma::vec y, arma::mat x, arma::vec radius_seq, arma::mat exposure, arma::mat w, arma::mat full_dists, double metrop_var_rho_theta, arma::vec metrop_var_gamma, arma::vec metrop_var_phi_star, double metrop_var_rho_phi, int likelihood_indicator, Rcpp::Nullable<Rcpp::NumericVector> offset, Rcpp::Nullable<Rcpp::NumericVector> trials, Rcpp::Nullable<double> a_r_prior, Rcpp::Nullable<double> b_r_prior, Rcpp::Nullable<double> a_sigma2_epsilon_prior, Rcpp::Nullable<double> b_sigma2_epsilon_prior, Rcpp::Nullable<double> sigma2_beta_prior, Rcpp::Nullable<double> a_sigma2_theta_prior, Rcpp::Nullable<double> b_sigma2_theta_prior, Rcpp::Nullable<double> l_rho_theta_prior, Rcpp::Nullable<double> u_rho_theta_prior, Rcpp::Nullable<double> sigma2_gamma_prior, Rcpp::Nullable<double> a_sigma2_phi_prior, Rcpp::Nullable<double> b_sigma2_phi_prior, Rcpp::Nullable<double> a_rho_phi_prior, Rcpp::Nullable<double> b_rho_phi_prior, Rcpp::Nullable<double> r_init, Rcpp::Nullable<double> sigma2_epsilon_init, Rcpp::Nullable<Rcpp::NumericVector> beta_init, Rcpp::Nullable<double> theta_keep_init, Rcpp::Nullable<double> sigma2_theta_init, Rcpp::Nullable<double> rho_theta_init, Rcpp::Nullable<Rcpp::NumericVector> gamma_init, Rcpp::Nullable<double> sigma2_phi_init, Rcpp::Nullable<double> rho_phi_init);
RcppExport SEXP _SpBuffer_SpatialBuffers(SEXP mcmc_samplesSEXP, SEXP ySEXP, SEXP xSEXP, SEXP radius_seqSEXP, SEXP exposureSEXP, SEXP wSEXP, SEXP full_distsSEXP, SEXP metrop_var_rho_thetaSEXP, SEXP metrop_var_gammaSEXP, SEXP metrop_var_phi_starSEXP, SEXP metrop_var_rho_phiSEXP, SEXP likelihood_indicatorSEXP, SEXP offsetSEXP, SEXP trialsSEXP, SEXP a_r_priorSEXP, SEXP b_r_priorSEXP, SEXP a_sigma2_epsilon_priorSEXP, SEXP b_sigma2_epsilon_priorSEXP, SEXP sigma2_beta_priorSEXP, SEXP a_sigma2_theta_priorSEXP, SEXP b_sigma2_theta_priorSEXP, SEXP l_rho_theta_priorSEXP, SEXP u_rho_theta_priorSEXP, SEXP sigma2_gamma_priorSEXP, SEXP a_sigma2_phi_priorSEXP, SEXP b_sigma2_phi_priorSEXP, SEXP a_rho_phi_priorSEXP, SEXP b_rho_phi_priorSEXP, SEXP r_initSEXP, SEXP sigma2_epsilon_initSEXP, SEXP beta_initSEXP, SEXP theta_keep_initSEXP, SEXP sigma2_theta_initSEXP, SEXP rho_theta_initSEXP, SEXP gamma_initSEXP, SEXP sigma2_phi_initSEXP, SEXP rho_phi_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mcmc_samples(mcmc_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_seq(radius_seqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type full_dists(full_distsSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_rho_theta(metrop_var_rho_thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_var_gamma(metrop_var_gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_var_phi_star(metrop_var_phi_starSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_rho_phi(metrop_var_rho_phiSEXP);
    Rcpp::traits::input_parameter< int >::type likelihood_indicator(likelihood_indicatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type trials(trialsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_r_prior(a_r_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_r_prior(b_r_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_epsilon_prior(a_sigma2_epsilon_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_epsilon_prior(b_sigma2_epsilon_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_beta_prior(sigma2_beta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_theta_prior(a_sigma2_theta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_theta_prior(b_sigma2_theta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type l_rho_theta_prior(l_rho_theta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type u_rho_theta_prior(u_rho_theta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_gamma_prior(sigma2_gamma_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_phi_prior(a_sigma2_phi_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_phi_prior(b_sigma2_phi_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_rho_phi_prior(a_rho_phi_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_rho_phi_prior(b_rho_phi_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type r_init(r_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_epsilon_init(sigma2_epsilon_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type theta_keep_init(theta_keep_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_theta_init(sigma2_theta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type rho_theta_init(rho_theta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_phi_init(sigma2_phi_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type rho_phi_init(rho_phi_initSEXP);
    rcpp_result_gen = Rcpp::wrap(SpatialBuffers(mcmc_samples, y, x, radius_seq, exposure, w, full_dists, metrop_var_rho_theta, metrop_var_gamma, metrop_var_phi_star, metrop_var_rho_phi, likelihood_indicator, offset, trials, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_beta_prior, a_sigma2_theta_prior, b_sigma2_theta_prior, l_rho_theta_prior, u_rho_theta_prior, sigma2_gamma_prior, a_sigma2_phi_prior, b_sigma2_phi_prior, a_rho_phi_prior, b_rho_phi_prior, r_init, sigma2_epsilon_init, beta_init, theta_keep_init, sigma2_theta_init, rho_theta_init, gamma_init, sigma2_phi_init, rho_phi_init));
    return rcpp_result_gen;
END_RCPP
}
// beta_update
arma::vec beta_update(arma::mat x, arma::vec off_set, int n_ind, int p_x, double sigma2_beta, arma::vec omega, arma::vec lambda, arma::vec theta_keep_old, arma::mat Z);
RcppExport SEXP _SpBuffer_beta_update(SEXP xSEXP, SEXP off_setSEXP, SEXP n_indSEXP, SEXP p_xSEXP, SEXP sigma2_betaSEXP, SEXP omegaSEXP, SEXP lambdaSEXP, SEXP theta_keep_oldSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type p_x(p_xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_beta(sigma2_betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep_old(theta_keep_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_update(x, off_set, n_ind, p_x, sigma2_beta, omega, lambda, theta_keep_old, Z));
    return rcpp_result_gen;
END_RCPP
}
// gamma_update
Rcpp::List gamma_update(arma::mat x, arma::vec radius_seq, arma::mat exposure, arma::vec off_set, arma::mat w, int n_ind, int m, int p_w, arma::rowvec one_vec, double sigma2_gamma, arma::vec omega, arma::vec lambda, arma::vec beta, arma::vec theta, arma::vec gamma_old, arma::vec phi_tilde, arma::vec delta_star_trans, arma::vec delta_star, arma::vec radius_pointer, arma::mat G, arma::vec radius, arma::mat Z, arma::vec theta_keep, arma::vec metrop_var_gamma, arma::vec acctot_gamma);
RcppExport SEXP _SpBuffer_gamma_update(SEXP xSEXP, SEXP radius_seqSEXP, SEXP exposureSEXP, SEXP off_setSEXP, SEXP wSEXP, SEXP n_indSEXP, SEXP mSEXP, SEXP p_wSEXP, SEXP one_vecSEXP, SEXP sigma2_gammaSEXP, SEXP omegaSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP gamma_oldSEXP, SEXP phi_tildeSEXP, SEXP delta_star_transSEXP, SEXP delta_starSEXP, SEXP radius_pointerSEXP, SEXP GSEXP, SEXP radiusSEXP, SEXP ZSEXP, SEXP theta_keepSEXP, SEXP metrop_var_gammaSEXP, SEXP acctot_gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_seq(radius_seqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type p_w(p_wSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type one_vec(one_vecSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_gamma(sigma2_gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_old(gamma_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi_tilde(phi_tildeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_star_trans(delta_star_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_star(delta_starSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_pointer(radius_pointerSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep(theta_keepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_var_gamma(metrop_var_gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type acctot_gamma(acctot_gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_update(x, radius_seq, exposure, off_set, w, n_ind, m, p_w, one_vec, sigma2_gamma, omega, lambda, beta, theta, gamma_old, phi_tilde, delta_star_trans, delta_star, radius_pointer, G, radius, Z, theta_keep, metrop_var_gamma, acctot_gamma));
    return rcpp_result_gen;
END_RCPP
}
// latent_update
Rcpp::List latent_update(arma::vec y, arma::mat x, arma::vec off_set, arma::vec tri_als, int likelihood_indicator, int n_ind, int r_old, arma::vec beta_old, arma::vec theta_keep_old, arma::mat Z);
RcppExport SEXP _SpBuffer_latent_update(SEXP ySEXP, SEXP xSEXP, SEXP off_setSEXP, SEXP tri_alsSEXP, SEXP likelihood_indicatorSEXP, SEXP n_indSEXP, SEXP r_oldSEXP, SEXP beta_oldSEXP, SEXP theta_keep_oldSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tri_als(tri_alsSEXP);
    Rcpp::traits::input_parameter< int >::type likelihood_indicator(likelihood_indicatorSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type r_old(r_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_old(beta_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep_old(theta_keep_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(latent_update(y, x, off_set, tri_als, likelihood_indicator, n_ind, r_old, beta_old, theta_keep_old, Z));
    return rcpp_result_gen;
END_RCPP
}
// neg_two_loglike_update
double neg_two_loglike_update(arma::vec y, arma::mat x, arma::vec off_set, arma::vec tri_als, int likelihood_indicator, int n_ind, int r, double sigma2_epsilon, arma::vec beta, arma::vec theta_keep, arma::mat Z);
RcppExport SEXP _SpBuffer_neg_two_loglike_update(SEXP ySEXP, SEXP xSEXP, SEXP off_setSEXP, SEXP tri_alsSEXP, SEXP likelihood_indicatorSEXP, SEXP n_indSEXP, SEXP rSEXP, SEXP sigma2_epsilonSEXP, SEXP betaSEXP, SEXP theta_keepSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tri_als(tri_alsSEXP);
    Rcpp::traits::input_parameter< int >::type likelihood_indicator(likelihood_indicatorSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep(theta_keepSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(neg_two_loglike_update(y, x, off_set, tri_als, likelihood_indicator, n_ind, r, sigma2_epsilon, beta, theta_keep, Z));
    return rcpp_result_gen;
END_RCPP
}
// phi_star_update
Rcpp::List phi_star_update(arma::mat x, arma::vec radius_seq, arma::mat exposure, arma::vec off_set, arma::mat w, int n_ind, int n_grid, int m, arma::rowvec one_vec, arma::vec omega, arma::vec lambda, arma::vec beta, arma::vec theta, arma::vec gamma, arma::vec phi_star_old, double sigma2_phi_old, arma::mat phi_star_corr_inv, arma::mat C, arma::vec phi_tilde, arma::vec delta_star_trans, arma::vec delta_star, arma::vec radius_pointer, arma::mat G, arma::vec radius, arma::mat Z, arma::vec theta_keep, arma::vec metrop_var_phi_star, arma::vec acctot_phi_star);
RcppExport SEXP _SpBuffer_phi_star_update(SEXP xSEXP, SEXP radius_seqSEXP, SEXP exposureSEXP, SEXP off_setSEXP, SEXP wSEXP, SEXP n_indSEXP, SEXP n_gridSEXP, SEXP mSEXP, SEXP one_vecSEXP, SEXP omegaSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP gammaSEXP, SEXP phi_star_oldSEXP, SEXP sigma2_phi_oldSEXP, SEXP phi_star_corr_invSEXP, SEXP CSEXP, SEXP phi_tildeSEXP, SEXP delta_star_transSEXP, SEXP delta_starSEXP, SEXP radius_pointerSEXP, SEXP GSEXP, SEXP radiusSEXP, SEXP ZSEXP, SEXP theta_keepSEXP, SEXP metrop_var_phi_starSEXP, SEXP acctot_phi_starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_seq(radius_seqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type one_vec(one_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi_star_old(phi_star_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_phi_old(sigma2_phi_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phi_star_corr_inv(phi_star_corr_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi_tilde(phi_tildeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_star_trans(delta_star_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_star(delta_starSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_pointer(radius_pointerSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep(theta_keepSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_var_phi_star(metrop_var_phi_starSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type acctot_phi_star(acctot_phi_starSEXP);
    rcpp_result_gen = Rcpp::wrap(phi_star_update(x, radius_seq, exposure, off_set, w, n_ind, n_grid, m, one_vec, omega, lambda, beta, theta, gamma, phi_star_old, sigma2_phi_old, phi_star_corr_inv, C, phi_tilde, delta_star_trans, delta_star, radius_pointer, G, radius, Z, theta_keep, metrop_var_phi_star, acctot_phi_star));
    return rcpp_result_gen;
END_RCPP
}
// r_update
int r_update(arma::vec y, arma::mat x, arma::vec off_set, int n_ind, int a_r, int b_r, arma::vec beta, arma::vec theta_keep, arma::mat Z);
RcppExport SEXP _SpBuffer_r_update(SEXP ySEXP, SEXP xSEXP, SEXP off_setSEXP, SEXP n_indSEXP, SEXP a_rSEXP, SEXP b_rSEXP, SEXP betaSEXP, SEXP theta_keepSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< int >::type b_r(b_rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep(theta_keepSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(r_update(y, x, off_set, n_ind, a_r, b_r, beta, theta_keep, Z));
    return rcpp_result_gen;
END_RCPP
}
// radius_update
Rcpp::List radius_update(arma::vec y, arma::mat x, arma::vec radius_seq, arma::mat exposure, arma::vec off_set, arma::vec tri_als, int likelihood_indicator, int n_ind, int m, int r_old, double sigma2_epsilon, arma::vec beta, arma::vec theta, arma::mat Z, arma::vec theta_keep);
RcppExport SEXP _SpBuffer_radius_update(SEXP ySEXP, SEXP xSEXP, SEXP radius_seqSEXP, SEXP exposureSEXP, SEXP off_setSEXP, SEXP tri_alsSEXP, SEXP likelihood_indicatorSEXP, SEXP n_indSEXP, SEXP mSEXP, SEXP r_oldSEXP, SEXP sigma2_epsilonSEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP ZSEXP, SEXP theta_keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_seq(radius_seqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tri_als(tri_alsSEXP);
    Rcpp::traits::input_parameter< int >::type likelihood_indicator(likelihood_indicatorSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type r_old(r_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep(theta_keepSEXP);
    rcpp_result_gen = Rcpp::wrap(radius_update(y, x, radius_seq, exposure, off_set, tri_als, likelihood_indicator, n_ind, m, r_old, sigma2_epsilon, beta, theta, Z, theta_keep));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_pgdraw
arma::vec rcpp_pgdraw(arma::vec b, arma::vec c);
RcppExport SEXP _SpBuffer_rcpp_pgdraw(SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pgdraw(b, c));
    return rcpp_result_gen;
END_RCPP
}
// rho_phi_update
Rcpp::List rho_phi_update(arma::mat x, arma::vec radius_seq, arma::mat exposure, arma::vec off_set, arma::mat w, int n_ind, int m, arma::mat dists12, arma::mat dists22, arma::rowvec one_vec, double a_rho_phi, double b_rho_phi, arma::vec omega, arma::vec lambda, arma::vec beta, arma::vec theta, arma::vec gamma, arma::vec phi_star, double sigma2_phi, double rho_phi_old, Rcpp::List phi_star_corr_info, arma::mat C, arma::vec phi_tilde, arma::vec delta_star_trans, arma::vec delta_star, arma::vec radius_pointer, arma::mat G, arma::vec radius, arma::mat Z, arma::vec theta_keep, double metrop_var_rho_phi, int acctot_rho_phi);
RcppExport SEXP _SpBuffer_rho_phi_update(SEXP xSEXP, SEXP radius_seqSEXP, SEXP exposureSEXP, SEXP off_setSEXP, SEXP wSEXP, SEXP n_indSEXP, SEXP mSEXP, SEXP dists12SEXP, SEXP dists22SEXP, SEXP one_vecSEXP, SEXP a_rho_phiSEXP, SEXP b_rho_phiSEXP, SEXP omegaSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP gammaSEXP, SEXP phi_starSEXP, SEXP sigma2_phiSEXP, SEXP rho_phi_oldSEXP, SEXP phi_star_corr_infoSEXP, SEXP CSEXP, SEXP phi_tildeSEXP, SEXP delta_star_transSEXP, SEXP delta_starSEXP, SEXP radius_pointerSEXP, SEXP GSEXP, SEXP radiusSEXP, SEXP ZSEXP, SEXP theta_keepSEXP, SEXP metrop_var_rho_phiSEXP, SEXP acctot_rho_phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_seq(radius_seqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dists12(dists12SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dists22(dists22SEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type one_vec(one_vecSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho_phi(a_rho_phiSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho_phi(b_rho_phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi_star(phi_starSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_phi(sigma2_phiSEXP);
    Rcpp::traits::input_parameter< double >::type rho_phi_old(rho_phi_oldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type phi_star_corr_info(phi_star_corr_infoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi_tilde(phi_tildeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_star_trans(delta_star_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_star(delta_starSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius_pointer(radius_pointerSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep(theta_keepSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_rho_phi(metrop_var_rho_phiSEXP);
    Rcpp::traits::input_parameter< int >::type acctot_rho_phi(acctot_rho_phiSEXP);
    rcpp_result_gen = Rcpp::wrap(rho_phi_update(x, radius_seq, exposure, off_set, w, n_ind, m, dists12, dists22, one_vec, a_rho_phi, b_rho_phi, omega, lambda, beta, theta, gamma, phi_star, sigma2_phi, rho_phi_old, phi_star_corr_info, C, phi_tilde, delta_star_trans, delta_star, radius_pointer, G, radius, Z, theta_keep, metrop_var_rho_phi, acctot_rho_phi));
    return rcpp_result_gen;
END_RCPP
}
// rho_theta_update
Rcpp::List rho_theta_update(int m, double l_rho_theta, double u_rho_theta, arma::vec theta, double sigma2_theta, double rho_theta_old, Rcpp::List theta_corr_info, double metrop_var_rho_theta, int acctot_rho_theta_trans);
RcppExport SEXP _SpBuffer_rho_theta_update(SEXP mSEXP, SEXP l_rho_thetaSEXP, SEXP u_rho_thetaSEXP, SEXP thetaSEXP, SEXP sigma2_thetaSEXP, SEXP rho_theta_oldSEXP, SEXP theta_corr_infoSEXP, SEXP metrop_var_rho_thetaSEXP, SEXP acctot_rho_theta_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type l_rho_theta(l_rho_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type u_rho_theta(u_rho_thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_theta(sigma2_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type rho_theta_old(rho_theta_oldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type theta_corr_info(theta_corr_infoSEXP);
    Rcpp::traits::input_parameter< double >::type metrop_var_rho_theta(metrop_var_rho_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type acctot_rho_theta_trans(acctot_rho_theta_transSEXP);
    rcpp_result_gen = Rcpp::wrap(rho_theta_update(m, l_rho_theta, u_rho_theta, theta, sigma2_theta, rho_theta_old, theta_corr_info, metrop_var_rho_theta, acctot_rho_theta_trans));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_epsilon_update
double sigma2_epsilon_update(arma::vec y, arma::mat x, arma::vec off_set, int n_ind, double a_sigma2_epsilon, double b_sigma2_epsilon, arma::vec beta_old, arma::vec theta_keep_old, arma::mat Z);
RcppExport SEXP _SpBuffer_sigma2_epsilon_update(SEXP ySEXP, SEXP xSEXP, SEXP off_setSEXP, SEXP n_indSEXP, SEXP a_sigma2_epsilonSEXP, SEXP b_sigma2_epsilonSEXP, SEXP beta_oldSEXP, SEXP theta_keep_oldSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_epsilon(a_sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_epsilon(b_sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_old(beta_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_keep_old(theta_keep_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_epsilon_update(y, x, off_set, n_ind, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, theta_keep_old, Z));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_phi_update
double sigma2_phi_update(int n_grid, double a_sigma2_phi, double b_sigma2_phi, arma::vec phi_star, arma::mat phi_star_corr_inv);
RcppExport SEXP _SpBuffer_sigma2_phi_update(SEXP n_gridSEXP, SEXP a_sigma2_phiSEXP, SEXP b_sigma2_phiSEXP, SEXP phi_starSEXP, SEXP phi_star_corr_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_grid(n_gridSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_phi(a_sigma2_phiSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_phi(b_sigma2_phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi_star(phi_starSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phi_star_corr_inv(phi_star_corr_invSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_phi_update(n_grid, a_sigma2_phi, b_sigma2_phi, phi_star, phi_star_corr_inv));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_theta_update
double sigma2_theta_update(int m, double a_sigma2_theta, double b_sigma2_theta, arma::vec theta, double rho_theta_old, arma::mat theta_corr_inv);
RcppExport SEXP _SpBuffer_sigma2_theta_update(SEXP mSEXP, SEXP a_sigma2_thetaSEXP, SEXP b_sigma2_thetaSEXP, SEXP thetaSEXP, SEXP rho_theta_oldSEXP, SEXP theta_corr_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_theta(a_sigma2_thetaSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_theta(b_sigma2_thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type rho_theta_old(rho_theta_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta_corr_inv(theta_corr_invSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_theta_update(m, a_sigma2_theta, b_sigma2_theta, theta, rho_theta_old, theta_corr_inv));
    return rcpp_result_gen;
END_RCPP
}
// spatial_corr_fun
Rcpp::List spatial_corr_fun(double phi, arma::mat spatial_dists);
RcppExport SEXP _SpBuffer_spatial_corr_fun(SEXP phiSEXP, SEXP spatial_distsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type spatial_dists(spatial_distsSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_corr_fun(phi, spatial_dists));
    return rcpp_result_gen;
END_RCPP
}
// temporal_corr_fun
Rcpp::List temporal_corr_fun(int m, double rho_theta);
RcppExport SEXP _SpBuffer_temporal_corr_fun(SEXP mSEXP, SEXP rho_thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type rho_theta(rho_thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(temporal_corr_fun(m, rho_theta));
    return rcpp_result_gen;
END_RCPP
}
// theta_single_update
Rcpp::List theta_single_update(arma::mat x, arma::vec off_set, int n_ind, int m, arma::vec omega, arma::vec lambda, arma::vec beta, double sigma2_theta_old, double rho_theta_old, arma::mat theta_corr_inv, double radius_pointer_old, arma::mat Z);
RcppExport SEXP _SpBuffer_theta_single_update(SEXP xSEXP, SEXP off_setSEXP, SEXP n_indSEXP, SEXP mSEXP, SEXP omegaSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP sigma2_theta_oldSEXP, SEXP rho_theta_oldSEXP, SEXP theta_corr_invSEXP, SEXP radius_pointer_oldSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_theta_old(sigma2_theta_oldSEXP);
    Rcpp::traits::input_parameter< double >::type rho_theta_old(rho_theta_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta_corr_inv(theta_corr_invSEXP);
    Rcpp::traits::input_parameter< double >::type radius_pointer_old(radius_pointer_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(theta_single_update(x, off_set, n_ind, m, omega, lambda, beta, sigma2_theta_old, rho_theta_old, theta_corr_inv, radius_pointer_old, Z));
    return rcpp_result_gen;
END_RCPP
}
// theta_update
Rcpp::List theta_update(arma::mat x, arma::vec off_set, int n_ind, int m, arma::rowvec one_vec, arma::vec omega, arma::vec lambda, arma::vec beta, double sigma2_theta_old, double rho_theta_old, arma::mat theta_corr_inv, arma::mat G, arma::mat Z);
RcppExport SEXP _SpBuffer_theta_update(SEXP xSEXP, SEXP off_setSEXP, SEXP n_indSEXP, SEXP mSEXP, SEXP one_vecSEXP, SEXP omegaSEXP, SEXP lambdaSEXP, SEXP betaSEXP, SEXP sigma2_theta_oldSEXP, SEXP rho_theta_oldSEXP, SEXP theta_corr_invSEXP, SEXP GSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type off_set(off_setSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type one_vec(one_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_theta_old(sigma2_theta_oldSEXP);
    Rcpp::traits::input_parameter< double >::type rho_theta_old(rho_theta_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta_corr_inv(theta_corr_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(theta_update(x, off_set, n_ind, m, one_vec, omega, lambda, beta, sigma2_theta_old, rho_theta_old, theta_corr_inv, G, Z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpBuffer_SingleBuffer", (DL_FUNC) &_SpBuffer_SingleBuffer, 25},
    {"_SpBuffer_SpatialBuffers", (DL_FUNC) &_SpBuffer_SpatialBuffers, 37},
    {"_SpBuffer_beta_update", (DL_FUNC) &_SpBuffer_beta_update, 9},
    {"_SpBuffer_gamma_update", (DL_FUNC) &_SpBuffer_gamma_update, 25},
    {"_SpBuffer_latent_update", (DL_FUNC) &_SpBuffer_latent_update, 10},
    {"_SpBuffer_neg_two_loglike_update", (DL_FUNC) &_SpBuffer_neg_two_loglike_update, 11},
    {"_SpBuffer_phi_star_update", (DL_FUNC) &_SpBuffer_phi_star_update, 28},
    {"_SpBuffer_r_update", (DL_FUNC) &_SpBuffer_r_update, 9},
    {"_SpBuffer_radius_update", (DL_FUNC) &_SpBuffer_radius_update, 15},
    {"_SpBuffer_rcpp_pgdraw", (DL_FUNC) &_SpBuffer_rcpp_pgdraw, 2},
    {"_SpBuffer_rho_phi_update", (DL_FUNC) &_SpBuffer_rho_phi_update, 32},
    {"_SpBuffer_rho_theta_update", (DL_FUNC) &_SpBuffer_rho_theta_update, 9},
    {"_SpBuffer_sigma2_epsilon_update", (DL_FUNC) &_SpBuffer_sigma2_epsilon_update, 9},
    {"_SpBuffer_sigma2_phi_update", (DL_FUNC) &_SpBuffer_sigma2_phi_update, 5},
    {"_SpBuffer_sigma2_theta_update", (DL_FUNC) &_SpBuffer_sigma2_theta_update, 6},
    {"_SpBuffer_spatial_corr_fun", (DL_FUNC) &_SpBuffer_spatial_corr_fun, 2},
    {"_SpBuffer_temporal_corr_fun", (DL_FUNC) &_SpBuffer_temporal_corr_fun, 2},
    {"_SpBuffer_theta_single_update", (DL_FUNC) &_SpBuffer_theta_single_update, 12},
    {"_SpBuffer_theta_update", (DL_FUNC) &_SpBuffer_theta_update, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpBuffer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
