# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FixedBuffer <- function(mcmc_samples, y, x, q, v, radius, exposure_definition_indicator, exposure_dists, likelihood_indicator, waic_info_indicator = NULL, offset = NULL, trials = NULL, a_r_prior = NULL, b_r_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, sigma2_eta_prior = NULL, r_init = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, eta_init = NULL) {
    .Call(`_EpiBuffer_FixedBuffer`, mcmc_samples, y, x, q, v, radius, exposure_definition_indicator, exposure_dists, likelihood_indicator, waic_info_indicator, offset, trials, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_beta_prior, sigma2_eta_prior, r_init, sigma2_epsilon_init, beta_init, eta_init)
}

SingleBuffer <- function(mcmc_samples, y, x, q, v, radius_range, exposure_definition_indicator, exposure_dists, metrop_var_radius, likelihood_indicator, waic_info_indicator = NULL, offset = NULL, trials = NULL, a_r_prior = NULL, b_r_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, sigma2_eta_prior = NULL, r_init = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, eta_init = NULL, radius_init = NULL) {
    .Call(`_EpiBuffer_SingleBuffer`, mcmc_samples, y, x, q, v, radius_range, exposure_definition_indicator, exposure_dists, metrop_var_radius, likelihood_indicator, waic_info_indicator, offset, trials, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_beta_prior, sigma2_eta_prior, r_init, sigma2_epsilon_init, beta_init, eta_init, radius_init)
}

SpatialBuffers <- function(mcmc_samples, y, x, q, w, v, radius_range, exposure_definition_indicator, exposure_dists, full_dists, metrop_var_gamma, metrop_var_phi_star, metrop_var_tau_phi, metrop_var_rho_phi, likelihood_indicator, waic_info_indicator = NULL, offset = NULL, trials = NULL, a_r_prior = NULL, b_r_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, sigma2_eta_prior = NULL, a_rho_phi_prior = NULL, b_rho_phi_prior = NULL, r_init = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, eta_init = NULL, gamma_init = NULL, tau_phi_init = NULL, rho_phi_init = NULL) {
    .Call(`_EpiBuffer_SpatialBuffers`, mcmc_samples, y, x, q, w, v, radius_range, exposure_definition_indicator, exposure_dists, full_dists, metrop_var_gamma, metrop_var_phi_star, metrop_var_tau_phi, metrop_var_rho_phi, likelihood_indicator, waic_info_indicator, offset, trials, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_beta_prior, sigma2_eta_prior, a_rho_phi_prior, b_rho_phi_prior, r_init, sigma2_epsilon_init, beta_init, eta_init, gamma_init, tau_phi_init, rho_phi_init)
}

beta_update <- function(x, off_set, n_ind, p_x, sigma2_beta, omega, lambda, eta_old, Z) {
    .Call(`_EpiBuffer_beta_update`, x, off_set, n_ind, p_x, sigma2_beta, omega, lambda, eta_old, Z)
}

eta_update <- function(x, off_set, n_ind, p_q, sigma2_eta, omega, lambda, beta, Z) {
    .Call(`_EpiBuffer_eta_update`, x, off_set, n_ind, p_q, sigma2_eta, omega, lambda, beta, Z)
}

gamma_update <- function(radius_range, exposure_definition_indicator, v_exposure_dists, p_q, n_ind, m, m_max, p_w, x, q, v_w, v_index, off_set, omega, lambda, beta, eta, gamma_old, radius, radius_trans, phi_tilde, exposure, Z, metrop_var_gamma, acctot_gamma) {
    .Call(`_EpiBuffer_gamma_update`, radius_range, exposure_definition_indicator, v_exposure_dists, p_q, n_ind, m, m_max, p_w, x, q, v_w, v_index, off_set, omega, lambda, beta, eta, gamma_old, radius, radius_trans, phi_tilde, exposure, Z, metrop_var_gamma, acctot_gamma)
}

latent_update <- function(y, x, off_set, tri_als, likelihood_indicator, n_ind, r_old, beta_old, eta_old, Z) {
    .Call(`_EpiBuffer_latent_update`, y, x, off_set, tri_als, likelihood_indicator, n_ind, r_old, beta_old, eta_old, Z)
}

neg_two_loglike_update <- function(y, x, off_set, tri_als, likelihood_indicator, n_ind, r, sigma2_epsilon, beta, eta, Z) {
    .Call(`_EpiBuffer_neg_two_loglike_update`, y, x, off_set, tri_als, likelihood_indicator, n_ind, r, sigma2_epsilon, beta, eta, Z)
}

phi_star_update <- function(radius_range, exposure_definition_indicator, v_exposure_dists, p_q, n_ind, n_grid, m, m_max, p_w, x, q, v_w, v_index, off_set, omega, lambda, beta, eta, gamma, radius, radius_trans, phi_star, phi_tilde, phi_star_corr_inv, C, exposure, Z, metrop_var_phi_star, acctot_phi_star) {
    .Call(`_EpiBuffer_phi_star_update`, radius_range, exposure_definition_indicator, v_exposure_dists, p_q, n_ind, n_grid, m, m_max, p_w, x, q, v_w, v_index, off_set, omega, lambda, beta, eta, gamma, radius, radius_trans, phi_star, phi_tilde, phi_star_corr_inv, C, exposure, Z, metrop_var_phi_star, acctot_phi_star)
}

r_update <- function(y, x, off_set, n_ind, a_r, b_r, beta, eta, Z) {
    .Call(`_EpiBuffer_r_update`, y, x, off_set, n_ind, a_r, b_r, beta, eta, Z)
}

radius_update <- function(radius_range, exposure_definition_indicator, v_exposure_dists, p_q, n_ind, m, m_max, x, q, off_set, omega, lambda, beta, eta, radius_old, radius_trans_old, exposure, Z, metrop_var_radius, acctot_radius) {
    .Call(`_EpiBuffer_radius_update`, radius_range, exposure_definition_indicator, v_exposure_dists, p_q, n_ind, m, m_max, x, q, off_set, omega, lambda, beta, eta, radius_old, radius_trans_old, exposure, Z, metrop_var_radius, acctot_radius)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_EpiBuffer_rcpp_pgdraw`, b, c)
}

rho_phi_update <- function(radius_range, exposure_definition_indicator, v_exposure_dists, p_q, n_ind, n_grid, m, m_max, p_w, x, q, v_w, v_index, off_set, dists12, dists22, a_rho_phi, b_rho_phi, omega, lambda, beta, eta, gamma, radius, rho_phi_old, radius_trans, phi_star, phi_tilde, phi_star_corr_info, C, exposure, Z, metrop_var_rho_phi, acctot_rho_phi) {
    .Call(`_EpiBuffer_rho_phi_update`, radius_range, exposure_definition_indicator, v_exposure_dists, p_q, n_ind, n_grid, m, m_max, p_w, x, q, v_w, v_index, off_set, dists12, dists22, a_rho_phi, b_rho_phi, omega, lambda, beta, eta, gamma, radius, rho_phi_old, radius_trans, phi_star, phi_tilde, phi_star_corr_info, C, exposure, Z, metrop_var_rho_phi, acctot_rho_phi)
}

sigma2_epsilon_update <- function(y, x, off_set, n_ind, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, eta_old, Z) {
    .Call(`_EpiBuffer_sigma2_epsilon_update`, y, x, off_set, n_ind, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, eta_old, Z)
}

spatial_corr_fun <- function(phi, spatial_dists) {
    .Call(`_EpiBuffer_spatial_corr_fun`, phi, spatial_dists)
}

tau_phi_update <- function(n_grid, tau_phi_old, phi_star, phi_star_corr_inv, metrop_var_tau_phi, acctot_tau_phi) {
    .Call(`_EpiBuffer_tau_phi_update`, n_grid, tau_phi_old, phi_star, phi_star_corr_inv, metrop_var_tau_phi, acctot_tau_phi)
}

